# Generated by Django 3.2.5 on 2021-08-19 08:50

import datetime
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(default='Guest Author', max_length=20)),
                ('author_img', models.ImageField(null=True, upload_to='upload')),
                ('author_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_feild', models.CharField(default='Others', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='blogpost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='N/A', max_length=50)),
                ('content', tinymce.models.HTMLField()),
                ('blog_img', models.ImageField(null=True, upload_to='upload')),
                ('publish_date', models.DateField(default=datetime.datetime.today)),
                ('blog_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AceInc.author')),
                ('blog_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AceInc.category')),
            ],
        ),
    ]
