# Generated by Django 3.2.5 on 2021-08-20 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AceInc', '0003_category_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='blog_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='AceInc.category'),
        ),
    ]
