# Generated by Django 3.2.5 on 2021-08-20 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AceInc', '0004_alter_blogpost_blog_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='blog_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='category', to='AceInc.category'),
        ),
    ]
