# Generated by Django 3.2.5 on 2021-08-20 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AceInc', '0005_alter_blogpost_blog_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='blog_category',
            field=models.CharField(default='Others', max_length=20),
        ),
    ]
