# Generated by Django 3.2.5 on 2021-08-20 17:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AceInc', '0006_alter_blogpost_blog_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_data', models.TextField()),
                ('name_data', models.CharField(default='Guest', max_length=20)),
                ('comment_date', models.DateField(default=datetime.datetime.today)),
                ('parent_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_id', to='AceInc.blogpost')),
            ],
        ),
    ]
