# Generated by Django 3.2.5 on 2021-08-20 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AceInc', '0007_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='about_auth',
            field=models.CharField(default='Deny to disclose', max_length=30),
        ),
    ]
